name: base
channels:
  - conda-forge
dependencies:
  - conda
  - python=3.9
  - python.app
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator==2.3.2
  - navigator-updater
  - geopandas
  - seaborn
  - descartes
  - mpld3
  - folium
  - panel
  - scikit-learn
  - selenium
  - phantomjs


# Group 2